# -*- coding: utf-8 -*-
"""notebook_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iXgVGafq0d6FMbIefJVDa-1NcBVB8DnW
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

!pip install tensorflow # Install tensorflow
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import (
    Dense, Dropout, BatchNormalization,
    GlobalAveragePooling2D
)
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

from sklearn.metrics import classification_report, confusion_matrix
from sklearn.utils.class_weight import compute_class_weight

import kagglehub

# Download latest version
path = kagglehub.dataset_download("shufanshahi/eye-disease-image-dataset")

print("Path to dataset files:", path)

import os
import pandas as pd

# Function to collect filepaths and labels
def get_filepaths_and_labels(root_dir):
    filepaths = []
    labels = []
    # Assuming the dataset structure is root_dir/Eye_Disease/CLASS_NAME/image.jpg
    dataset_base_dir = os.path.join(root_dir, 'Eye_Disease')
# Check if 'Eye_Disease' subdirectory exists, otherwise use root_dir directly
    if not os.path.isdir(dataset_base_dir):
        dataset_base_dir = root_dir

    for dirpath, dirnames, filenames in os.walk(dataset_base_dir):
        for filename in filenames:
            # Filter for common image file extensions
            if filename.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp')):
                filepath = os.path.join(dirpath, filename)
                # The label is typically the name of the immediate parent directory
                label = os.path.basename(os.path.dirname(filepath))
                filepaths.append(filepath)
                labels.append(label)
    return filepaths, labels
    # 'path' variable is already defined from a previous cell
all_filepaths, all_labels = get_filepaths_and_labels(path)

# Create the DataFrame
df = pd.DataFrame({
    'filepaths': all_filepaths,
    'labels': all_labels
})

# Display the head of the DataFrame to verify it's created correctly
df.head()

from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
import os

# The dataframe 'df' already contains the filepaths and labels, which is more reliable.
# Use df to get class names and counts.

# Get class names from the 'labels' column of the DataFrame
class_names = sorted(df['labels'].unique().tolist())
print("Classes:", class_names)

# Count images per class using value_counts from the DataFrame
image_counts = df['labels'].value_counts().to_dict()

print(image_counts)

# Plot
plt.figure(figsize=(12, 5))
sns.barplot(
    x=list(image_counts.keys()),
    y=list(image_counts.values())
)
plt.xticks(rotation=45, ha='right')
plt.title('Number of Images per Class')
plt.ylabel('Count')
plt.xlabel('Class')
plt.tight_layout()
plt.show()

# حذف Glaucoma من الـ DataFrame
df = df[df["labels"] != "Glaucoma"].reset_index(drop=True)

# تأكيد
print(df["labels"].value_counts())

# حذف Macular Scar من الـ DataFrame
df = df[df["labels"] != "Macular Scar"].reset_index(drop=True)

# تأكيد
print(df["labels"].value_counts())

# حذف Macular Scar من الـ DataFrame
df = df[df["labels"] != "Central Serous Chorioretinopathy"].reset_index(drop=True)

# تأكيد
print(df["labels"].value_counts())

DATASET_DIR = "/kaggle/input/eye-disease-image-dataset"
TRAIN_DIR = os.path.join(DATASET_DIR, "train")
TEST_DIR  = os.path.join(DATASET_DIR, "test")

print(len(df))
df.head()

classes = df['labels'].unique().tolist()
print("Classes:", classes)

print("\nImage counts per class:")
for cls in classes:
    count = (df['labels'] == cls).sum()
    print(f"{cls}: {count}")

IMG_SIZE = (300,300)
BATCH_SIZE = 32
NUM_CLASSES = len(classes)

from tensorflow.keras.applications.efficientnet import preprocess_input

train_datagen = ImageDataGenerator(
    preprocessing_function=preprocess_input,
    rotation_range=15,
    zoom_range=0.2,
    horizontal_flip=True,
    validation_split=0.2
)

test_datagen = ImageDataGenerator(
    preprocessing_function=preprocess_input
)

from sklearn.model_selection import train_test_split

train_val_df, test_df = train_test_split(
    df,
    test_size=0.2,
    random_state=42,
    stratify=df["labels"]
)

train_df, val_df = train_test_split(
    train_val_df,
    test_size=0.25,   # 0.25 × 0.8 = 0.2
    random_state=42,
    stratify=train_val_df["labels"]
)

train_generator = train_datagen.flow_from_dataframe(
    dataframe=train_df,
    x_col='filepaths',
    y_col='labels',
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="categorical",
    shuffle=True
)
validation_generator = test_datagen.flow_from_dataframe(
    dataframe=val_df,
    x_col='filepaths',
    y_col='labels',
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="categorical",
    shuffle=False
)
test_generator = test_datagen.flow_from_dataframe(
    dataframe=test_df,
    x_col='filepaths',
    y_col='labels',
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="categorical",
    shuffle=False
)

print("Train:", len(train_df))
print("Validation:", len(val_df))
print("Test:", len(test_df))

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Use the current state of df to get class names and counts
class_names = sorted(df['labels'].unique().tolist())
print("Classes (after removals):", class_names)

# Count images per class using value_counts from the DataFrame
image_counts = df['labels'].value_counts().to_dict()

print("Image counts per class (after removals):")
for cls, count in image_counts.items():
    print(f"{cls}: {count}")

df_counts = pd.DataFrame({
    "Class": image_counts.keys(),
    "Original_Count": image_counts.values()
})

print(df_counts)

# Plot
plt.figure(figsize=(12, 5))
sns.barplot(
    x=list(image_counts.keys()),
    y=list(image_counts.values())
)
plt.xticks(rotation=45, ha='right')
plt.title('Number of Images per Class (after removals)')
plt.ylabel('Count')
plt.xlabel('Class')
plt.tight_layout()
plt.show()

from sklearn.utils.class_weight import compute_class_weight
import numpy as np

labels = train_df["labels"]

class_weights_vals = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(labels),
    y=labels
)

class_weights_named = dict(zip(np.unique(labels), class_weights_vals))
print(class_weights_named)

df_counts = train_df["labels"].value_counts().to_frame(name="Original_Count")

df_counts["Class_Weight"] = df_counts.index.map(class_weights_named)

df_counts["Balanced_Effective_Count"] = (
    df_counts["Original_Count"] * df_counts["Class_Weight"]
)

print(df_counts)

from sklearn.utils.class_weight import compute_class_weight
import numpy as np

labels = train_generator.classes  # indices: 0,1,2,...

class_weights = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(labels),
    y=labels
)

class_weights = dict(zip(np.unique(labels), class_weights))

print("class_weights:", class_weights)

plt.figure(figsize=(14,5))

plt.subplot(1,2,1)
plt.bar(df_counts.index, df_counts["Original_Count"])
plt.title("Before Balance")
plt.xticks(rotation=45, ha="right")

plt.subplot(1,2,2)
plt.bar(df_counts.index, df_counts["Balanced_Effective_Count"])
plt.title("After Balance (Correct Class Weights)")
plt.xticks(rotation=45, ha="right")

plt.tight_layout()
plt.show()

base_model = keras.applications.EfficientNetB3(
    include_top=False,
    weights="imagenet",
    input_shape=(300,300, 3)
)
base_model.trainable = False

from tensorflow.keras.layers import (
    Dense,
    Dropout,
    GlobalAveragePooling2D,
    BatchNormalization
)
from tensorflow import keras

# عدد الكلاسات (دايمًا خده من generator)
NUM_CLASSES = len(train_generator.class_indices)

x = base_model.output
x = GlobalAveragePooling2D()(x)
x = BatchNormalization()(x)

x = Dense(
    256,
    activation='relu',
    kernel_initializer='he_normal',
    kernel_regularizer=keras.regularizers.l2(1e-4)
)(x)

x = Dropout(0.5)(x)

output = Dense(NUM_CLASSES, activation='softmax')(x)

model = keras.Model(inputs=base_model.input, outputs=output)

# Explicitly build the model to ensure all variables are created
model.build(input_shape=(None, IMG_SIZE[0], IMG_SIZE[1], 3))

from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint

callbacks = [
    EarlyStopping(
        monitor="val_loss",
        patience=3,
        restore_best_weights=True,
        verbose=1
    ),

    ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.3,
        patience=2,
        min_lr=1e-5,
        verbose=1
    ),

    ModelCheckpoint(
    "best_efficientnetb3.keras",   # 🔥 بدل .h5
    monitor="val_loss",
    save_best_only=True,
    mode="min",
    verbose=1
)
]

import tensorflow as tf

model.compile(
    optimizer=keras.optimizers.Adam(1e-3),
    loss="categorical_crossentropy",
    metrics=[
        "accuracy",
        tf.keras.metrics.AUC(name="auc"),   # 👈 مهم
        tf.keras.metrics.Recall(name="recall")
    ]
)

history = model.fit(
    train_generator,
    validation_data=validation_generator,  # أو val_generator
    epochs=15,
    class_weight=class_weights,
    callbacks=callbacks
)

import numpy as np
from sklearn.metrics import classification_report

# Predict
y_pred = model.predict(test_generator)
y_pred_classes = np.argmax(y_pred, axis=1)
y_true = test_generator.classes

class_labels = list(test_generator.class_indices.keys())

print("Classification Report:\n")
print(classification_report(
    y_true,
    y_pred_classes,
    target_names=class_labels,
    digits=2
))



import seaborn as sns
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_true, y_pred_classes)

plt.figure(figsize=(8,6))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=class_labels,
    yticklabels=class_labels
)

plt.title("Confusion Matrix - EfficientNetB3")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.tight_layout()



plt.show()

# =====================================
# 🔥 GRAD-CAM++ (ADVANCED VERSION)
# =====================================

import tensorflow as tf
import numpy as np
import cv2
import matplotlib.pyplot as plt

LAST_CONV_LAYER = "top_conv"


# =====================================
# 🔹 Grad-CAM++ Heatmap
# =====================================
def make_gradcam_plus_plus(img_array, model, last_conv_layer_name):

    grad_model = tf.keras.models.Model(
        inputs=model.input,
        outputs=[
            model.get_layer(last_conv_layer_name).output,
            model.output
        ]
    )

    with tf.GradientTape() as tape:
        conv_outputs, predictions = grad_model(img_array)
        pred_index = tf.argmax(predictions[0])
        loss = predictions[:, pred_index]

    grads = tape.gradient(loss, conv_outputs)[0]
    conv_outputs = conv_outputs[0]

    # 🔥 Grad-CAM++ weights
    grads_squared = tf.square(grads)
    grads_cubed = grads_squared * grads

    denominator = 2 * grads_squared + tf.reduce_sum(
        conv_outputs * grads_cubed, axis=(0, 1), keepdims=True
    )

    denominator = tf.where(denominator != 0, denominator, tf.ones_like(denominator))

    alphas = grads_squared / denominator

    weights = tf.reduce_sum(alphas * tf.nn.relu(grads), axis=(0, 1))

    # Heatmap
    heatmap = tf.reduce_sum(conv_outputs * weights, axis=-1)

    # Normalize
    heatmap = tf.maximum(heatmap, 0)
    heatmap /= tf.reduce_max(heatmap) + 1e-8

    return heatmap.numpy(), int(pred_index)


# =====================================
# 🔹 Visualization (Smooth + Pro)
# =====================================
def show_gradcam_plus_plus(img_path):

    # Load image
    img = tf.keras.preprocessing.image.load_img(img_path, target_size=IMG_SIZE)
    img_array = tf.keras.preprocessing.image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)

    img_array = tf.keras.applications.efficientnet.preprocess_input(img_array)

    # Heatmap
    heatmap, pred_idx = make_gradcam_plus_plus(
        img_array, model, LAST_CONV_LAYER
    )

    class_names = list(train_generator.class_indices.keys())
    pred_label = class_names[pred_idx]

    # Original image
    original = cv2.imread(img_path)
    original = cv2.cvtColor(original, cv2.COLOR_BGR2RGB)
    original = cv2.resize(original, IMG_SIZE)

    # Resize
    heatmap = cv2.resize(heatmap, (IMG_SIZE[1], IMG_SIZE[0]))

    # Normalize
    heatmap = np.maximum(heatmap, 0)
    heatmap /= np.max(heatmap) + 1e-8

    # Convert to 0-255
    heatmap = np.uint8(255 * heatmap)

    # 🔥 Smooth قوي جدًا
    heatmap = cv2.GaussianBlur(heatmap, (31, 31), 0)

    # Color
    heatmap_color = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)

    # Overlay (احترافي)
    overlay = cv2.addWeighted(original, 0.7, heatmap_color, 0.3, 0)

    # =====================================
    # 🔹 Plot
    # =====================================
    plt.figure(figsize=(12,4))

    plt.subplot(1,3,1)
    plt.imshow(original)
    plt.title("Original Image")
    plt.axis("off")

    plt.subplot(1,3,2)
    plt.imshow(heatmap, cmap="jet")
    plt.title("Grad-CAM++")
    plt.axis("off")

    plt.subplot(1,3,3)
    plt.imshow(overlay)
    plt.title(f"Prediction: {pred_label}")
    plt.axis("off")

    plt.tight_layout()
    plt.show()

    print("Prediction:", pred_label)


# =====================================
# 🔹 Run
# =====================================
img_path = "/kaggle/input/datasets/shufanshahi/eye-disease-image-dataset/Eye Disease Image Dataset/Original Dataset/Healthy/Healthy1011.jpg"

show_gradcam_plus_plus(img_path)



!pip install transformers accelerate bitsandbytes -q

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image

# تحميل موديل EfficientNet
vision_model = load_model('best_efficientnetb3.h5')

class_names = [
    'Diabetic Retinopathy',
    'Disc Edema',
    'Healthy',
    'Myopia',
    'Pterygium',
    'Retinal Detachment',
    'Retinitis Pigmentosa'
]

print("Vision model loaded successfully!")

from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model_name = "microsoft/Phi-3-mini-4k-instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)

llm_model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16,
    device_map="auto"
)

print("Phi-3 loaded successfully!")

def predict_disease(img_path):
    img = image.load_img(img_path, target_size=(224, 224))
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array = tf.keras.applications.efficientnet.preprocess_input(img_array)

    preds = vision_model.predict(img_array)
    class_idx = np.argmax(preds[0])
    confidence = float(np.max(preds[0]))
    disease = class_names[class_idx]

    return disease, confidence

def local_llm_explain(disease, confidence):

    device = "cuda" if torch.cuda.is_available() else "cpu"

    prompt = f"""
You are an ophthalmology AI.

Write exactly 5 short medical lines about this prediction:

Prediction: {disease}
Confidence: {confidence:.2f}

Structure:
1. Prediction statement.
2. Short definition.
3. Key symptoms.
4. Severity level.
5. What to do next.

Only write the 5 lines. No titles. No repetition.
"""

    inputs = tokenizer(prompt, return_tensors="pt").to(device)

    outputs = llm_model.generate(
        **inputs,
        max_new_tokens=120,
        temperature=0.1,
        do_sample=False,
        repetition_penalty=1.2
    )

    text = tokenizer.decode(outputs[0], skip_special_tokens=True)

    # حذف البرومبت من البداية
    cleaned = text.replace(prompt, "").strip()

    lines = cleaned.split("\n")
    final_output = "\n".join(lines[:5])

    return final_output.strip()

original, heatmap, overlay = generate_gradcam_plus_plus(img_path)

disease, conf = predict_disease("/kaggle/input/datasets/shufanshahi/eye-disease-image-dataset/Eye Disease Image Dataset/Original Dataset/Retinal Detachment/Retinal Detachment100.jpg")

print(f"Predicted disease: {disease}")
print(f"Confidence: {conf:.2f}")

print("\nAI Medical Report:\n")

report = local_llm_explain(disease, conf)
print(report)
print("\nGrad-CAM:\n")

plt.figure(figsize=(12,4))

# 🔹 Original
plt.subplot(1,3,1)
plt.imshow(original)
plt.title("Original Image")
plt.axis("off")

# 🔹 Heatmap
plt.subplot(1,3,2)
plt.imshow(heatmap, cmap="jet")
plt.title("Grad-CAM++")
plt.axis("off")

# 🔹 Overlay
plt.subplot(1,3,3)
plt.imshow(overlay)
plt.title(f"Prediction: {disease}")
plt.axis("off")

plt.tight_layout()
plt.show()

